package eu.siacs.conversations.xml;

public final class Namespace {
	public static final String DISCO_ITEMS = "http://jabber.org/protocol/disco#items";
	public static final String DISCO_INFO = "http://jabber.org/protocol/disco#info";
	public static final String BLOCKING = "urn:xmpp:blocking";
	public static final String ROSTER = "jabber:iq:roster";
	public static final String REGISTER = "jabber:iq:register";
	public static final String BYTE_STREAMS = "http://jabber.org/protocol/bytestreams";
	public static final String HTTP_UPLOAD = "urn:xmpp:http:upload:0";
	public static final String HTTP_UPLOAD_LEGACY = "urn:xmpp:http:upload";
	public static final String STANZA_IDS = "urn:xmpp:sid:0";
	public static final String IDLE = "urn:xmpp:idle:1";
	public static final String DATA = "jabber:x:data";
	public static final String OOB = "jabber:x:oob";
	public static final String SASL = "urn:ietf:params:xml:ns:xmpp-sasl";
	public static final String TLS = "urn:ietf:params:xml:ns:xmpp-tls";
	public static final String PUBSUB = "http://jabber.org/protocol/pubsub";
	public static final String PUBSUB_PUBLISH_OPTIONS = PUBSUB+"#publish-options";
	public static final String PUBSUB_ERROR = PUBSUB+"#errors";
	public static final String PUBSUB_OWNER = PUBSUB+"#owner";
	public static final String NICK = "http://jabber.org/protocol/nick";
	public static final String FLEXIBLE_OFFLINE_MESSAGE_RETRIEVAL = "http://jabber.org/protocol/offline";
	public static final String BIND = "urn:ietf:params:xml:ns:xmpp-bind";
	public static final String P1_S3_FILE_TRANSFER = "p1:s3filetransfer";
	public static final String BOOKMARKS_CONVERSION = "urn:xmpp:bookmarks-conversion:0";
	public static final String BOOKMARKS = "storage:bookmarks";
	public static final String SYNCHRONIZATION = "im.quicksy.synchronization:0";
	public static final String AVATAR_CONVERSION = "urn:xmpp:pep-vcard-conversion:0";
	public static final String JINGLE_TRANSPORTS_S5B = "urn:xmpp:jingle:transports:s5b:1";
	public static final String JINGLE_TRANSPORTS_IBB = "urn:xmpp:jingle:transports:ibb:1";
	public static final String IBB = "http://jabber.org/protocol/ibb";
	public static final String PING = "urn:xmpp:ping";
	public static final String PUSH = "urn:xmpp:push:0";
	public static final String COMMANDS = "http://jabber.org/protocol/commands";
	public static final String JINGLE_ENCRYPTED_TRANSPORT = "urn:xmpp:jingle:jet:0";
	public static final String JINGLE_ENCRYPTED_TRANSPORT_OMEMO = "urn:xmpp:jingle:jet-omemo:0";
	public static final String MUC_USER = "http://jabber.org/protocol/muc#user";
	public static final String BOOKMARKS2 = "urn:xmpp:bookmarks:0";
	public static final String BOOKMARKS2_COMPAT = BOOKMARKS2+"#compat";
	public static final String INVITE = "urn:xmpp:invite";
	public static final String PARS = "urn:xmpp:pars:0";
}
